id: P50364D57
initial_creation_type: input
source_metadata:
  title: Dorje Dechen Lingpa Series
  language: en
  description: The following texts are available in our series of texts by or about
    Dorje Dechen Lingpa (rdo rje bde chen gling pa, 1857–1928), the reincarnation
    of Yongdzin Jinpa Gyatso, who founded Domang Monastery, and Lhatsün Namkha Jigme.
  volume:
    ca08d6e4cc1a4d67ae293f41b25d1b96:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: null
created_at: '2022-02-28T23:02:55.947534'
last_modified_at: '2022-02-28T23:02:55.947540'
